### ISSUE TITLE
can't find artefact in maven repository 

### ISSUE THREAD

**Issue by otmanesabir** [finazon-io/finazon-grpc-java#1]
Hey, 

I'm trying to integrate the java client into a small prototype application but can't find the package in maven. 
I checked maven central and also couldn't find anything there. 

Am I missing something?

**Comment by nhnick** [comment]
There were some problems with publishing library to Maven Central. Now it's working: https://central.sonatype.com/artifact/io.finazon/finazon-grpc-java/overview
